import React, { useState } from 'react';
import axios from 'axios';

function App() {
  const [clientId, setClientId] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null); // 'clean' | 'banned'
  const [evidence, setEvidence] = useState(null);
  const [appealed, setAppealed] = useState(false);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!clientId) return;
    setLoading(true);
    setResult(null);
    setEvidence(null);
    
    try {
      const res = await axios.get(`http://localhost:4000/api/v1/players/${clientId}/trust`, {
        headers: { 'x-sentinx-signature': 'dev-override-token' }
      });
      
      const isBanned = res.data.is_banned;
      setResult(isBanned ? 'banned' : 'clean');
      setAppealed(false);
      
      if (isBanned) {
        try {
          const evRes = await axios.get(`http://localhost:4000/api/v1/appeals/${clientId}/evidence`, {
            headers: { 'x-sentinx-signature': 'dev-override-token' }
          });
          setEvidence(evRes.data.evidence);
        } catch (e) {
          setEvidence("Error: Could not retrieve PyTorch tensor from Cold Storage.");
        }
      }
    } catch (err) {
      setResult('clean');
    }
    setLoading(false);
  };

  return (
    <div className="container">
      <h1 className="header">SentinelX Ban Appeal</h1>
      <p className="subtitle">Enter your SteamID to verify your account standing.</p>

      <form className="search-form" onSubmit={handleSearch}>
        <input 
          type="text" 
          className="search-input" 
          placeholder="SteamID (e.g. 76561198...)" 
          value={clientId}
          onChange={(e) => setClientId(e.target.value)}
        />
        <button type="submit" className="btn" disabled={loading}>
          {loading ? 'Checking...' : 'Check Status'}
        </button>
      </form>

      {result === 'clean' && (
        <div className="result-box clean">
          <div className="status-title" style={{color: '#008000'}}>Status: Clean</div>
          <p>No active bans or heuristic violations were found for <strong>{clientId}</strong>.</p>
        </div>
      )}

      {result === 'banned' && (
        <div className="result-box banned">
          <div className="status-title" style={{color: '#cc0000'}}>Status: Permanently Banned</div>
          <p>This account was permanently suspended by the SentinelX Machine Learning pipeline for anomalous behavior.</p>
          
          <div style={{marginTop: '24px', padding: '16px', background: '#fff', border: '1px solid #ddd', borderRadius: '4px'}}>
            <h3 style={{marginBottom: '8px', fontSize: '18px'}}>Submit an Appeal</h3>
            <p style={{fontSize: '14px', color: '#666', marginBottom: '16px'}}>
              If you believe this ban was a false positive generated by our neural network, you may request a manual review by a human Game Master.
            </p>
            {appealed ? (
              <div style={{color: '#0066cc', fontWeight: 'bold'}}>✓ Appeal submitted successfully. Your case is pending review.</div>
            ) : (
              <button className="btn" onClick={() => setAppealed(true)}>Submit Appeal</button>
            )}
          </div>

          <h4 style={{marginTop: '24px', marginBottom: '8px'}}>Cold Storage Evidence (Raw Tensor)</h4>
          <div className="evidence-block">
            {evidence ? JSON.stringify(evidence, null, 2) : "Fetching..."}
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
