import React, { useState } from 'react';
import axios from 'axios';
import { Search, ShieldAlert, ShieldCheck } from 'lucide-react';

function App() {
  const [clientId, setClientId] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null); // 'clean' | 'banned'
  const [evidence, setEvidence] = useState(null);
  const [appealed, setAppealed] = useState(false);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!clientId) return;
    setLoading(true);
    setResult(null);
    setEvidence(null);
    
    try {
      const res = await axios.get(`http://localhost:4000/api/v1/players/${clientId}/trust`, {
        headers: { 'x-sentinx-signature': 'dev-override-token' }
      });
      
      const isBanned = res.data.is_banned;
      setResult(isBanned ? 'banned' : 'clean');
      setAppealed(false);
      
      if (isBanned) {
        try {
          const evRes = await axios.get(`http://localhost:4000/api/v1/appeals/${clientId}/evidence`, {
            headers: { 'x-sentinx-signature': 'dev-override-token' }
          });
          setEvidence(evRes.data.evidence);
        } catch (e) {
          setEvidence("Error: Could not retrieve PyTorch tensor from Cold Storage.");
        }
      }
    } catch (err) {
      setResult('clean');
    }
    setLoading(false);
  };

  return (
    <div className="portal-container">
      <div className="brand-header">
        <h1 className="brand-title">Ban Appeal Portal</h1>
        <p className="brand-subtitle">Enter your Account ID to verify your standing</p>
      </div>

      <form className="search-box" onSubmit={handleSearch}>
        <div style={{position: 'relative'}}>
            <Search size={18} color="#9ca3af" style={{position: 'absolute', left: '16px', top: '16px'}} />
            <input 
            type="text" 
            className="input-field" 
            style={{paddingLeft: '44px'}}
            placeholder="Account ID (e.g. 1001)" 
            value={clientId}
            onChange={(e) => setClientId(e.target.value)}
            />
        </div>
        <button type="submit" className="btn-primary" disabled={loading || !clientId}>
          {loading ? 'Checking...' : 'Check Status'}
        </button>
      </form>

      {result === 'clean' && (
        <div className="result-card">
          <div className="status-badge clean"><ShieldCheck size={14} style={{display:'inline', verticalAlign:'middle', marginRight:'4px'}}/> Active and Clean</div>
          <h2 className="result-title">No actions taken</h2>
          <p className="result-text">We found no active bans or heuristic violations for <strong>{clientId}</strong>. Your account is in good standing.</p>
        </div>
      )}

      {result === 'banned' && (
        <div className="result-card">
          <div className="status-badge banned"><ShieldAlert size={14} style={{display:'inline', verticalAlign:'middle', marginRight:'4px'}}/> Permanently Banned</div>
          <h2 className="result-title">Access Revoked</h2>
          <p className="result-text">This account was permanently suspended by the SentinelX Machine Learning pipeline for anomalous gameplay behavior.</p>
          
          <div className="appeal-box">
            <h3 style={{fontSize: '16px', fontWeight: 600, marginBottom: '8px'}}>Submit an Appeal</h3>
            <p className="result-text">If you believe this ban was a false positive generated by our neural network, you may request a manual review by a human Game Master.</p>
            {appealed ? (
              <div style={{color: 'var(--success)', fontWeight: 600, marginTop: '16px', fontSize: '14px', display: 'flex', alignItems: 'center', gap: '6px'}}>
                <ShieldCheck size={16} /> Appeal submitted successfully
              </div>
            ) : (
              <button className="btn-outline" onClick={() => setAppealed(true)}>Submit Appeal for Review</button>
            )}
          </div>

          <div style={{marginTop: '32px'}}>
              <h4 style={{fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.5px'}}>Cold Storage Evidence (Raw Tensor)</h4>
              <div className="code-block">
                {evidence ? JSON.stringify(evidence, null, 2) : "Fetching tensor..."}
              </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
